(function(){var g=void 0,i=true,l=null,m=false,n,o=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ca(){}
function da(a,b,c){switch(typeof b){case "string":ea(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),da(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),ea(e,c),c.push(":"),da(a,f,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var fa={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ga=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ea(a,b){b.push('"',a.replace(ga,function(a){if(a in fa)return fa[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return fa[a]=e+b.toString(16)}),'"')};var ha={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function ia(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ja(a,b){var c="",d=ka(encodeURIComponent(a));d.splice(b||5,d.length);p(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ka(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,h=3285377520,j=[],k,t,w,D,E,S=Math.ceil((a.length/4+2)/16),P=[S],y=0,v;y<S;y++){P[y]=[];for(k=0;k<16;k++)P[y][k]=a.charCodeAt(y*64+k*4)<<24|a.charCodeAt(y*64+k*4+1)<<16|a.charCodeAt(y*64+k*4+2)<<8|a.charCodeAt(y*64+k*4+3)}y=(a.length-1)*8;a=S-1;P[a][14]=Math.floor(y/Math.pow(2,32));P[a][15]=y&4294967295;for(y=0;y<S;y++){for(v=0;v<16;v++)j[v]=P[y][v];
for(v=16;v<80;v++)j[v]=(j[v-3]^j[v-8]^j[v-14]^j[v-16])<<1|(j[v-3]^j[v-8]^j[v-14]^j[v-16])>>>31;a=c;k=d;t=e;w=f;D=h;for(v=0;v<80;v++)E=Math.floor(v/20),E=(a<<5|a>>>27)+(E==0?k&t^~k&w:E==1?k^t^w:E==2?k&t^k&w^t&w:k^t^w)+D+b[E]+j[v]&4294967295,D=w,w=t,t=k<<30|k>>>2,k=a,a=E;c=c+a&4294967295;d=d+k&4294967295;e=e+t&4294967295;f=f+w&4294967295;h=h+D&4294967295}return[c,d,e,f,h]}
function la(a){var b=o.navigator,c=o.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];p(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=o.performance;d=d.concat([b&&b.now?b.now():"",document.title,o.location.href,q(),ia()]);return d.concat(a||[]).join()}function r(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function s(a){return typeof a!=="undefined"}function u(a){return a&&a.replace(/^www\./,"")}var ma=/^((https?\:)?(\/\/))/i;function na(a){return a&&a.replace(ma,"")}var oa=/^((https?\:)?(\/\/))?[^\/]*/;function pa(a){return a.replace(oa,"")}var qa=/\#.*/;function ra(a){return a.replace(qa,"")}var sa=/\?[^\#]*/;function ta(a){return a.toLowerCase()}var ua=/\/+((\?|\#).*)?$/;function va(a){return a.replace(ua,"$1")}function wa(a){return a&&a.replace(sa,"")}
function xa(a){var b=a.match(/\?(.*)$/ig)?a.match(/\?(.*)$/ig)[0].slice(1).replace(/#(.*)?/ig,"").split("&"):[],c=a.match(/#(.*)$/ig)?a.match(/#(.*)$/ig)[0]:"",a=a.match(/[#|\?](.*)?/ig)?a.slice(0,a.search(/[#|\?](.*)?/ig)):a,b=ya(b,function(a){return a.search("utm")!==0});b.length>0&&(a+="?"+b.join("&"));return a+c}function za(a,b){if(a===b)return 0;var c=l;p([ta,va,na,pa,ra,wa],function(d,e){a=d(a);b=d(b);if(a===b)return c=e+1,m});return c}
function x(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function Aa(a,b){var c=o;c.removeEventListener?c.removeEventListener(a,b,m):c.detachEvent&&c.detachEvent("on"+a,b)}function Ba(a){return typeof a==="number"}function z(a){return typeof a==="string"}function Ca(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function q(){return(new Date).getTime()}function Da(){return o.location.protocol==="http:"?"http:":"https:"}
function Ea(a){return!!a&&a.constructor===Object}function p(a,b){if(Ea(a)===i)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===m)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===m)break}}function Fa(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function ya(a,b){var c=[];p(a,function(a){b(a)&&c.push(a)});return c}
function Ga(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,h=a.length;f<=h;f++)c[0][f]=f;for(var j,k,t,d=1;d<=e;d++)for(f=1;f<=h;f++)j=d-1,k=f-1,t=c[j][k],b.charAt(j)==a.charAt(k)?c[d][f]=t:(k=c[d][k]+1,j=c[j][f]+1,t+=2,c[d][f]=Math.min(k,j,t));return c[b.length][a.length]}var Ha,Ia=o.setInterval,Ja=o.clearInterval,Ka=o.setTimeout,La=o.clearTimeout;
function Ma(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function Na(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),p(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Oa(a,b){var c="",d=o.location.href.match(/[^?]+[?]([^#]+).*/);if(d){var d=Na(d[1]),e=b||a;d[e]&&(c=d[e])}return encodeURIComponent(c)}function Pa(a,b){return!b?i:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Qa(a){var b=[];p(Ra,function(c){var d=a[c];s(d)&&(Object.prototype.toString.call(d)==="[object Array]"?p(d,function(a){b.push(c+"="+a)}):Ea(d)?p(d,function(a,c){b.push(c+"="+a)}):((d+"").length||c=="r")&&b.push(c+"="+d))});b.push("_");return b.join("&")}
function Sa(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=o.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=Pa(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?
"/"+a:e.substr(0,f)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Pa(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Ta(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function Ua(a,b,c,d){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+(a+(d?'="'+d+'"':""))+"]");for(var e=[],b=c.getElementsByTagName(b),c=b.length,f="";c--;)(f=b[c].getAttribute(a))&&(!d||f===d)&&e.push(b[c]);return e}function Va(a,b,c){c=c||"";if(a===g)a=m;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?m:Va(a.parentNode,b,c)}return a}
function Wa(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=Ua("data-cb-scroll-element"))&&c.length)return c[0][b];if(Ba(o[a]))return o[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function Xa(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}
function Ya(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Za(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return l;var d=a.ownerDocument.documentElement,e=0,f=s(c)?c+1:-1;z(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return l}
function $a(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function ab(a){a=a||window.event;return!a?l:Za(a.target||a.srcElement,$a,10)}function bb(a,b){var c=document.createElement(a);p(b,function(a,b){c.setAttribute(b,a)});return c};function cb(){this.G={};this.Ta=1}function A(a,b,c,d){a.Ta++;a.G[b]=a.G[b]||{};a.G[b][a.Ta]=[c,d];return a.Ta}function db(a,b){if(z(b))a.G[b]=g,delete a.G[b];else if(Ba(b)){var c=i;p(a.G,function(a){p(a,function(e,f){if(parseInt(f,10)===b)return a[f]=g,delete a[f],c=m});return c})}}cb.prototype.Q=function(a,b){if(this.G[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];p(this.G[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
cb.prototype.addEventListener=function(a,b){var c=A(this,a,b);b._cbEventId=c};cb.prototype.removeEventListener=function(a,b){this.G[a]&&this.G[a][b._cbEventId]&&this.G[a][b._cbEventId][0]===b&&db(this,b._cbEventId)};var B=new cb,eb="a";var C={};
C.D=function(){C.Ga?C.sa("pageload"):(C.vb=[{target:o,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:o,event:"resize"},{target:document.body,event:"mousedown"}],C.za=l,C.$=l,C.Fa={},C.gb={},p(C.vb,function(a){var b=a.event;x(a.target,b,function(a){C.sa.call(C,b,a)})}),A(B,"f",function(){C.sa("focus")}),C.sa("pageload"),x(document.body,"click",function(a){(a=ab(a))&&B.Q("c",a)},i),x(document.body,"contextmenu",function(a){(a=ab(a))&&B.Q("r",
a)}),C.Ga=i)};C.Ab=function(){var a,b=C.gb.keydown;if(b===g)return m;b=q()-b;return b<=(a||15E3)&&b>=0};C.Xa=100;C.sa=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}C.kc(a);if(C.za===l)C.pb(a);else if(!C.$||ha[C.$]<ha[a])C.$=a};C.kc=function(a){C.gb[a]=q()};C.pb=function(a){C.za=Ka(C.Fb,C.Xa);B.Q(eb);C.Fa[a]!==l&&La(C.Fa[a]);C.bc(a)};
C.bc=function(a){var b=C.Fa;b[a]=Ka(function(){La(b[a]);delete b[a];var c=m;p(b,function(){c=i;return m});c||B.Q("i")},ha[a]+C.Xa)};C.Fb=function(){La(C.za);C.za=l;if(C.$)C.pb(C.$),C.$=l};var fb,gb,hb,ib,jb;(function(){var a,b;p(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof o.document[a]==="boolean")return b=c,m});b!==g&&(ib=a,jb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),hb=b+"visibilitychange")})();var F=m;function kb(){F=jb&&o.document[jb]==="prerender"?i:m}function lb(){gb=i;B.Q("f")}function mb(){gb=m;B.Q("b")}
function nb(a,b,c){o.addEventListener?o.addEventListener(a,c,m):o.document.attachEvent&&o.document.attachEvent(b,c)}function ob(){var a=i;o.document.hasFocus&&(a=o.document.hasFocus());var b=m;ib&&(b=o.document[ib]);return a&&!b}function pb(){ob()?lb():mb()}function qb(a){kb();if(F){var b=m,c=function(){b||(kb(),F||(b=i,a(),o.window.setTimeout(function(){o.document.removeEventListener(hb,c,m)},100)))};o.document.addEventListener(hb,c,m)}else a()};function G(){this.a=o._sf_async_config||{};this.ab=r(this.kb,this)}G.prototype.D=function(){this.lb=0};G.prototype.kb=function(){};G.prototype.wa=function(a){if(!F){var b=this.ab,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};G.prototype.na=function(){this.ab=l};var H="path",I="domain",rb="useCanonical",sb="useCanonicalDomain",J="title",tb="virtualReferrer";function K(a,b,c){a[b]=a[b]||c}function ub(a,b){for(var c=o[a]||[];c.length;)b(c.shift());o[a]={push:b}}function vb(a){p(document.getElementsByTagName("script"),function(b){if(typeof b.src==="string"&&b.src.match(/chartbeat.js/))return b=Na(b.src.split("?")[1]),K(a,"uid",b.uid),K(a,I,b.domain),m})}function wb(a,b){return a[b]?encodeURIComponent(a[b]):""}
function xb(a){var b={};p(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};var L={};L.Db=function(a){try{L.create("_cb_test","1",1,a);var b=L.k("_cb_test");L.remove("_cb_test",a);return b==="1"}catch(c){return m}};L.k=function(a){a+="=";var b="";p(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),m});return b};
L.create=function(a,b,c,d){var e=o._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(q()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+("; path="+d);return document.cookie=a};L.remove=function(a,b){return L.k(a)?L.create(a,"",-86400,b):""};var M={};M.B=function(a){var b=o._sf_async_config;if(!a&&b&&b.noCookies)return l;if(M.B.Ca!==g)return M.B.Ca;var a=q()+"",c,d;try{if((d=o.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return M.B.Ca=d}catch(e){}return M.B.Ca=l};M.k=function(a){var b=M.B();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&q()>c)?(M.remove(a),""):b.getItem(a)||""};
M.create=function(a,b,c){var d=M.B();if(d){var e=new Date;e.setTime(q()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};M.remove=function(a){var b=M.B();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function yb(a,b){this.va=a||"";this.M=b||"/";this.Gb=M.B()!==l||L.Db(this.M);this.Sa=m;zb(this)}n=yb.prototype;n.isSupported=function(){return this.Gb};
function zb(a){if(!L.k("_cb_ls")){var b=M.B()!==l,c=L.k("_SUPERFLY_lockout");c&&p(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,i)});var d=L.k("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,i),L.remove("_chartbeat3",a.M));b&&((b=L.k("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,i),(b=L.k("_chartbeat5"))&&a.create("_chartbeat5",b,60,i));L.create("_cb_ls","1",34128E3,a.M)}}
n.create=function(a,b,c,d){a=d?a:this.va+a;(M.B()?M:L).create(a,b,c,this.M);M.B()&&L.create(a,b,c,this.M)};n.update=function(a,b,c,d,e,f,h){a=d?a:this.va+a;e=z(e)?e:"::";d=(d=this.k(a,i))?d.split(e):[];if(h&&d.length){var j=h(b),k=Fa(d,function(a){return h(a)===j});k!==-1&&d.splice(k,1)}d.push(b);for(Ba(f)&&d.length>f&&d.splice(0,d.length-f);d.length>1&&d.join(e).length>4E3;)d.shift();this.create(a,d.join(e),c,i)};
n.k=function(a,b){var a=b?a:this.va+a,c=(M.B()?M:L).k(a);if(!c&&M.B()&&(c=L.k(a))&&L.k("_cb_ls")){this.Sa=i;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}M.create(a,c,d)}return c};n.remove=function(a,b){a=b?a:this.va+a;(M.B()?M:L).remove(a,this.M);M.B()&&L.remove(a,this.M)};function Ab(a){var b=l;if(a&&(b=Bb(),b=!b?b:N(b.pathname)+b.search+b.hash))return b;var c=o.location,b=N(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Cb(a){return a&&(a=Bb(),a=!a?a:a.hostname)?a:o.location.hostname}function Bb(){var a=Db();return!a?a:Sa(a.href)}
function Db(){var a=l;p(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return a=b,m});return a}for(var Eb={},Fb=0;Fb<81;Fb++)Eb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Fb)]=i;function Gb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Eb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}
function N(a){if(!z(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Gb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function O(a,b){var c=Q();return s(b)&&!s(c[a])?b:c[a]}function Q(){s(o._cb_shared)||(o._cb_shared={});return o._cb_shared};var R={xb:{IDLE:0,wc:1,pc:2,wb:3},J:0};R.D=function(){if(!R.Ga)A(B,eb,R.Mb,R),A(B,"i",R.Pb,R),A(B,"f",R.Ob,R),A(B,"b",R.Nb,R),R.Ga=i};R.Kb=function(){return R.J};R.Mb=function(){R.J===1?R.O(3):R.J===0&&R.O(2)};R.Pb=function(){R.J===3?R.O(1):R.J===2&&R.O(0)};R.Ob=function(){(R.J===0||R.J===2)&&R.O(3)};R.Nb=function(){R.J===3?R.O(2):R.J===1&&R.O(0)};R.O=function(a){R.J=a;B.Q("s",a)};function Hb(a,b){this.Ea=a||g;this.La=b||g;this.ea=this.ba=0;this.Sb=r(this.Tb,this);this.rb=this.aa=l}n=Hb.prototype;n.D=function(){this.ea=this.ba=0;this.aa=l;this.rb=A(B,"s",this.eb,this);this.eb(R.Kb())};n.eb=function(a){Ja(this.aa);this.aa=l;if(a===R.xb.wb)this.aa=Ia(this.Sb,1E3)};n.Tb=function(){if(this.Ea===g||this.Ea())this.ba++,this.ea++,this.La&&this.La()};n.terminate=function(){Ja(this.aa);this.aa=l;db(B,this.rb)};n.na=function(){this.terminate();this.La=this.Ea=g};function T(){G.call(this);this.S=[];this.q=new yb(this.gc,this.a.cookiePath||"/");this.q.remove("_SUPERFLY_nosample");this.F=new Hb;this.Ma=r(this.ua,this);x(o,"unload",this.Ma);qb(r(this.D,this));this.Ha=m}ba(T,G);n=T.prototype;n.Qa=i;
n.D=function(){T.P.D.call(this);this.pa=this.U=0;this.ja=q();this.Pa=ja(Ib(this));this.Oa=i;this.Ia=72E5;if(this.Qa){var a=+this.a.sessionLength;if(!isNaN(a))this.Ia=a*6E4}a=O("d");if(!a){var a=[],b=this.q.k("_chartbeat2",i);b.length>0&&(a=b.split("."));a.length>6&&(a=[]);var b=q(),c=this.q.k("_cb",i);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),e=b-+(a[2]||0);Q().n=c&&d>18E5&&e<2592E6?0:1;var d=a[4],f=parseInt(a[5],10)||0;if(!(e=e>18E5))if(Jb(this))e=m;else{var e=U(this),e=decodeURIComponent(e),
e=Kb(e)||e,h;h=Lb(this);h=decodeURIComponent(h);h=Kb(h)||h;e=e!==h}!d||e?(d=ja(Ib(this)),a[4]=d,f=1,this.q.remove("_cb_svref",i)):f+=1;a[5]=f;f="1";e=a&&+a[2];d=a&&a[3];if(a&&e&&d)if(f=Math.abs((Ca(b)-Ca(e))/864E5)){f=Math.min(f,16)-1;for(e="";f--;)e+=0;f=(d+e+"1").slice(-16)}else f=d;d=f;c||(c=this.a.utoken||ja(Ib(this),3),a[1]=b);a[2]=b;a[3]=d;this.a.utoken=this.la;this.q.create("_cb",c,34128E3,i);this.q.create("_chartbeat2",a.join("."),34128E3,i);a[0]=c;Q().d=a}this.zc=a.join(".");var j;c=+a[1];
d=+a[2];if((b=a[3])&&c&&d)j=(Math.min((Math.abs((Ca(d)-Ca(c))/864E5)||0)+1,16,b.length)-1).toString(16),j+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.cb=j;this.Wb=O("n",1);this.la=a[0];this.fc=a[4];this.dc=a[5];this.ec=Lb(this);this.q.create("_cb_svref",Lb(this)||"null",1800,i);this.F.D();R.D();C.D();fb||(gb=ob(),hb&&o.document.addEventListener&&o.document.addEventListener(hb,pb,m),nb("focus","onfocusin",lb),nb("blur","onfocusout",mb),gb&&lb(),fb=i);this.fa=0;this.zb=A(B,eb,this.Yb,this)};
function Mb(a){if(!a.q.k("_SUPERFLY_lockout")&&!F)a.Ub?a.xa():(a.Ub=i,!o._sf_async_config&&!o._cbq?(a.ta=r(a.xa,a),x(o,"load",a.ta)):a.xa())}n.xa=function(){this.Na=Nb();C.D();var a=r(this.ga,this);this.fb=Ia(a,15E3);this.ga()};
n.ga=function(){var a=this.F.ea,a=this.a.reading&&+this.a.reading||a>0;if(this.pa<this.U&&!a)this.pa++;else{var b;if(Ha===g)b=o.navigator.userAgent,Ha=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Ha;b&&!a?this.pa++:(a?this.U=0:Ob(this),this.pa=0,this.S.push(0),this.S.length>18&&this.S.shift(),this.Qa&&q()-this.ja>=this.Ia?this.terminate():this.ia())}};
n.kb=function(){this.S.push(1);var a=0;p(this.S,function(b){a+=b});a<3?(this.Oa=i,Ob(this)):(this.terminate(),this.q.create("_SUPERFLY_lockout","1",600))};n.ua=function(){};n.Yb=function(){var a=Pb(this);this.fa=Math.max(this.fa,a)};function Pb(a){return Math.floor(Wa("Y","Top",!!a.a.scrollElement))}function Ob(a){var b=a.U,b=b?Math.min(b*2,16):1;a.U=b}n.oa=function(){this.ua();this.terminate()};n.qb=function(){this.Ha=i;this.D();Mb(this)};
function Jb(a){if(a.a[tb])return i;if(Qb(a))return m;a=document.referrer.indexOf("://"+o.location.hostname+"/");return a!=-1&&a<9}function Qb(a){var b=a.a.referrerOverrideQueryParam,c="";p(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),m});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function U(a){a=a.a[tb]||Qb(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=Sa(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=N(b.pathname),a=Ta(b)}return encodeURIComponent(a)}function Rb(a){a=a.a[J].slice(0,100);return encodeURIComponent(a)}function Ib(a){a=[U(a),Ya("Width"),Ya("Height")];return la(a)}function Sb(a){var b=[],c=a.q.k("_chartbeat4");c&&(p(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.q.remove("_chartbeat4"));return b}
function Lb(a){a=a.q.k("_cb_svref",i)||U(a)||"null";a==="null"&&(a="");return a}function Kb(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?l:a[1]}function Nb(){var a=o.performance&&o.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ba(b)&&b?Ba(a)&&a>b?a-b:q()-b:-1}n.terminate=function(){this.F.terminate();db(B,this.zb);this.ta!==g&&Aa("load",this.ta);Ja(this.fb);Q().d=g;Q().n=g};
n.na=function(){this.terminate();Aa("unload",this.Ma);this.Ma=this.ta=this.q=this.S=this.a=l;this.F.na();this.F=l;T.P.na.call(this)};function Tb(a){for(var b=O("m")||[];b.length;)a(b.shift());a={push:a};Q().m=a};function Ub(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=Vb(a);d+=f.x;e+=f.y;for(var h=m,j=c?0:Math.floor(Wa("X","Left",g)),k=c?0:Math.floor(Wa("Y","Top",g)),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=Vb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(Wb(a,["position"]).position==="fixed"){h=i;break}a=a.parentElement}c||(d-=b?b.scrollLeft:j,e-=b?b.scrollTop:k);h&&(d+=j,e+=k);return{x:d,y:e}}
function Wb(a,b){var c={},d,e;o.getComputedStyle?d=o.getComputedStyle(a,l):a.currentStyle?e="currentStyle":a.style&&(e="style");p(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var Xb=/matrix(3d)?\((.*)\)/;function Vb(a){var b={x:0,y:0},a=Wb(a,["transform"]).transform;if(!z(a))return b;var c=a.match(Xb);if(!c)return b;var a=c[2].split(", "),d;s(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};function Yb(){var a=o.location.href,a=a.replace(/-{2,}/g,"-"),a=Sa(a);a.pathname=N(a.pathname);return a}
function Zb(a){var b=L.k("_chartbeat6");if(!b)return l;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=Yb(),h=Ta(f);p(b,function(a,b){var f=a.split(","),k=Ga(h,decodeURIComponent(f[0]));if(k===0)return c=f,d=b,m;if(e===g||k<e)e=k,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+$b(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),j=c[2];c.splice(0,3);for(var k=c.length/3,t=0;t<k;t++){var w=t*3+2;a.push({xc:b,origin:f,X:j,Z:w<c.length?
c[w]:"",Hb:c[t*3],lc:c[t*3+1]})}return a}function $b(a){var b="",c;if(!Ea(a))return b;a.ib&&(c=new Date,c.setTime(c.getTime()+a.ib),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function ac(a){var b=a.topStorageDomain,a=a[I],c=o.location.hostname;return b?b:bc(c,a)?a:c.replace(/^www\./,"")}
function bc(a,b){if(a===b)return i;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return m;if(c.pop()!==d.pop())return m}return i}function cc(a,b,c,d,e){this.Jb=a;this.Ib=b;this.mc=c;this.X=d;this.Z=e}function dc(a){var b=a.d,c=l;if(b!==l){var d={};b.s&&p(b.s,function(a,b){d[b]=typeof a==="string"?{Za:a,Z:""}:{Za:a.chosenVariant,Z:a.specificLocation}});c={ob:d,X:b.g,hb:b.m}}return{status:a.s,data:c,code:a.c,message:a.m}};function ec(a,b){for(var c=b||document.documentElement,d=[],e=l,f=a,h,j,k,t,w,D;f&&f!==c;){h=f.nodeName.toLowerCase();e=f;j=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){k=f.children;t=0;for(w=0,D=k.length;w<D;w++){if(e===k[w]){h+="["+(1+w-t)+"]";break}k[w].nodeName!==j&&t++}}d.unshift(h)}return d.join("/")};function V(){this.gc="_t_";T.call(this)}ba(V,T);n=V.prototype;
n.D=function(){V.P.D.call(this);vb(this.a);var a=!!this.a[rb],b=Cb(!!this.a[sb]&&a);K(this.a,"mabServer","mabping.chartbeat.net");K(this.a,J,document.title);K(this.a,I,b);this.a[H]=this.a[H]?N(this.a[H]):Ab(a);this.da=u(b);this.a[I]=u(this.a[I]);this.jc=ac(this.a);this.ca=this.qa=m;this.bb=[];var c=this,a=Zb({domain:"."+this.jc,ib:6E4,path:"/"});if(a!==l)this.qa=i,p(a,function(a){c.bb.push(new cc(a.origin,a.Hb,a.lc,a.X,a.Z))});this.jb=0;this.ya=l;Tb(r(this.Rb,this))};
n.ia=function(){var a=this.F.ba,b=fc(this),c,d=this;this.qa&&p(this.bb,function(e){c=b+"&x="+e.Ib+"&v="+e.mc+"&ml="+e.X+"&xo="+e.Jb+"&e="+a+"&sl="+e.Z;d.wa(c)});!this.ca&&this.ya&&gc(this,this.ya);this.ca=i};n.xa=function(){this.Na=Nb();C.D();if(this.qa){var a=r(this.ga,this);this.fb=Ia(a,500)}this.ga()};n.ga=function(){var a,b;this.ca?(a=this.F.ba,b=this.jb*15,a-b>=15&&(this.ia(),this.jb+=1),a>=45&&this.terminate()):this.ia()};
function fc(a){var b=a.a;return Da()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b[I])+"&p="+encodeURIComponent(b[H])+"&d="+encodeURIComponent(a.da)+"&u="+a.la+"&c="+Math.round((q()-a.ja)/600)/100}n.ua=function(){};n.hc=function(a){a=dc(a);this.ca?gc(this,a):this.ya=a};
function gc(a,b){var c=fc(a),d=b.status,e=b.data;if(d=="s"&&e!==l){var f=r(a.wa,a);Ea(e.ob)&&p(e.ob,function(a,b){f(c+"&x="+b+"&v="+a.Za+"&ml="+e.X+"&sl="+a.Z+"&e=-1")});Object.prototype.toString.call(e.hb)==="[object Array]"&&p(e.hb,function(a){f(c+"&me=3&ml="+e.X+"&x="+a)})}else d=="e"&&a.wa(c+"&me="+b.code)}n.Rb=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.hc.apply(this,a):e==="v"&&this.cc.apply(this,a)}};
n.oa=function(){Q().m=[];s(this.Ua)&&this.Ua();V.P.oa.call(this)};n.cc=function(a){this.Ua=a};n.terminate=function(){this.Ua=this.yc=g;this.ya=l;this.ca=this.qa=g;V.P.terminate.call(this)};if(!L.k("cb_optout")&&!o.pSUPERFLY_mab){var hc=new V,ic={};ic.evps=r(hc.oa,hc);ic.svps=r(hc.qb,hc);o.pSUPERFLY_mab=ic;Mb(hc)};var jc="engagedSeconds",kc={uc:"id",tc:jc,qc:"campaignId",rc:"creativeId",vc:"placementId",sc:"element"};var lc,mc,W;
function nc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);oc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=s(g)?g:{},b.src=a,a=bb("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],s(g)?g.appendChild(a):b&&b.appendChild(a)}}
function oc(){La(mc);mc=g;Aa("message",nc);W&&W.parentNode&&W.parentNode.removeChild(W);W=g};function pc(){var a=o._sf_async_config&&o._sf_async_config.domain;if(a&&!lc){lc=i;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);x(o,"message",nc);mc=Ka(oc,1E4);var b=s(g)?g:{};b.src=a;a=bb("iframe",b);a.style.display="none";s(g)?g.appendChild(a):document.body&&document.body.appendChild(a);W=a}}
function qc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=M.B(i),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),pc(),Aa("message",qc))}};function rc(a,b){this.ub=b;this.tb=a[rb];this.sb=a[sb];this.N=a[H];this.ic=a[J];this.$a=a[I];this.oc=a[tb];this.Ya=(this.H=Bb())?this.H.hostname:"";this.ma=this.H?N(this.H.pathname)+this.H.search+this.H.hash:"";this.nb=Ab(m);this.ac=Cb(m);var c=Ua("property","meta",l,"og:url");this.ha=(this.Y=c&&c.length?Sa(c[0].content):l)?N(this.Y.pathname)+this.Y.search+this.Y.hash:"";this.Xb=this.Y?this.Y.hostname:"";this.Da=document.title||"";var d;if((c=Ua("property","meta",l,"og:title"))&&c.length)d=c[0].content;
this.ra=d;var e;if((d=Ua("property","meta",l,"twitter:title"))&&d.length)e=d[0].content;this.ka=e;e=!!this.tb;d=this.tb!==g;var c=!!this.sb,f=this.sb!==g,h=!!this.H,j;j=u(this.Ya);var k=u(this.ac);j=j===k;var k=!!this.ha,t=!this.H?m:this.ma===this.ha,w=this.ma===this.nb,D;D=this.ma;var E=wa(this.nb);D=D===E;var E=!!this.Da,S=!!this.ra,P=!!this.ka,y=this.Da===this.ra,v=!this.ka?m:this.Da===this.ka,zc=!this.ra||!this.ka?m:this.ra===this.ka,Ac=!!this.ic,Bc=!!this.N,Cc=this.N?this.N.charAt(0)!=="/":m,
Dc=!this.H?m:this.N===this.ma,Ec=!this.ha?m:this.N===this.ha,Fc=!this.H?m:this.$a===u(this.Ya),Gc=!this.ha?m:this.$a===u(this.Xb),Hc=!!this.ub,Ic=this.ub?m:!!this.oc,Jc=Da()==="https:",Kc=!!XMLHttpRequest,Z;this.N?(Z=xa(this.N),Z=Z!==wa(Z)):Z=m;e=[e,d,c,f,h,j,k,t,w,D,E,S,P,y,v,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Z];d=1;for(f=c=0;f<e.length;f++)c|=e[f]&&d,d<<=1;this.Eb=("00000000"+c.toString(16)).slice(-8)};function X(){"postMessage"in window&&x(o,"message",r(this.Qb,this));T.call(this);ub("_cbq",r(this.mb,this))}ba(X,T);
X.prototype.D=function(){X.P.D.call(this);var a=this.la;Q().u=a;a=this.Pa;Q().t=a;this.Vb=new rc(this.a,this.Ha);this.Ba=l;vb(this.a);var a=!!this.a[rb],b=Cb(!!this.a[sb]&&a);K(this.a,"pingServer","ping.chartbeat.net");K(this.a,J,document.title);K(this.a,I,b);this.a[H]=this.a[H]?N(this.a[H]):Ab(a);this.da=u(b);this.a[I]=u(this.a[I]);this.Bb=A(B,"c",this.Zb,this);this.Cb=A(B,"r",this.$b,this);this.T=l};X.prototype.yb=function(a){this.Ba=a};
X.prototype.ua=function(){this.q.update("_chartbeat4",["t="+this.Pa,"E="+this.F.ba,"x="+Pb(this),"c="+Math.round((q()-this.ja)/600)/100,"y="+Ya("Height"),"w="+Xa("Height")].join("&"),60,g,g,1)};var Ra="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,sv,sr,sd,im".split(",");n=X.prototype;
n.ia=function(a){this.lb++;var b={};b.g=this.a.uid;b.g0=wb(this.a,"sections");b.g1=wb(this.a,"authors");b.g2=wb(this.a,"zone");b.g3=wb(this.a,"sponsorName");b.g4=wb(this.a,"type");!this.a.noCookies&&this.q.isSupported()?b.n=this.Wb:b.nc=1;b.c=Math.round((q()-this.ja)/600)/100;b.E=this.F.ba;var c=Pb(this);this.fa=Math.max(this.fa,c);b.x=c;b.m=this.fa;b.y=Ya("Height");b.o=Ya("Width");b.w=Xa("Height");b.b=this.Na>0?this.Na:"";if(this.cb)b.f=this.cb;b[""]=xb(this.a);b.t=this.Pa;b.V=105;b.tz=(new Date).getTimezoneOffset();
b.sn=this.lb;b.sv=this.fc;b.sr=this.ec;b.sd=this.dc;c=this.F.ea;b.h=encodeURIComponent(this.a[I]);b.p=encodeURIComponent(this.a[H]);b.u=this.la;b.d=encodeURIComponent(this.da);b.j=Math.round((this.U+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;C.Ab()?b.W=1:this.a.reading&&+this.a.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Jb(this);if(this.Oa){this.Oa=m;if(c)this.T=sc(this);b.i=Rb(this);var d=this.a.hudTrackable;d!==g&&(b.L=d?"1":"0");this.a.alias&&(b.PA=encodeURIComponent(this.a.alias))}if(c){if(this.T){if(b.v=
encodeURIComponent(this.T.path),b.K=tc(this.T),this.T.Ka>1)b.l1=this.T.Ka}else b.v=U(this);this.Ha&&(b.vp=1)}else b.r=U(this);c=Ma(b.v);Q().v=c;c=Ma(b.r);Q().r=c;b.A=this.Ba?this.Ba:"";b._c=Oa("utm_campaign",this.a.campaignTag);b._m=Oa("utm_medium",this.a.mediumTag);b._x=Oa("utm_source",this.a.sourceTag);b._y=Oa("utm_content",this.a.contentTag);b._z=Oa("utm_term",this.a.termTag);b.im=this.Vb.Eb;this.a.idSync?(c=[],da(new ca,this.a.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=Sb(this);
b.C=this.a.mobileApp?1:"";b.KK=a?tc(a):"";a=this.q;c=a.Sa;a.Sa=m;b.l=c?1:"";this.F.ea=0;this.wa(Da()+"//"+this.a.pingServer+"/ping?"+Qa(b))};
n.Qb=function(a){var b=this.a,c=b.playerdomain||this.da;if(na(a.origin)===na(c))if(c=a.data,z(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.mb(a));else if(c=="cbdata?"){var c="&u="+O("u"),d="&t="+O("t"),e="&v="+O("v"),f="&r="+O("r"),b="domain="+encodeURIComponent(b[I])+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b[H])+"&title="+Rb(this)+"&referrer="+U(this)+"&internal="+(Jb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.da)+
c+d+e+f+"&utoken="+this.la;a.source.postMessage(b,"*")}};n.mb=function(a){a[0]==="_demo"&&this.a._demo?this.a._demo=this.a._demo+"%2C"+a[1]:this.a[a[0]]=a[1];this.U=0};function uc(a){a=a.replace(/-{2,}/g,"-");a=Sa(a);a.pathname=N(a.pathname);return a}n.Zb=function(a){vc(this,a,"c")};n.$b=function(a){vc(this,a,"r")};
function vc(a,b,c){if(a.Qa&&q()-a.ja>=a.Ia)a.terminate();else{var d=b.href||"",d=uc(d);if(d.protocol.indexOf("http")===0){var e=d.hostname!==o.location.hostname,d=Ta(d),f=Za(b,function(a){return a.id}),h=ec(b,f),j="";a.a.moduleAttribute&&(j=(j=Va(b,a.a.moduleAttribute))?j.getAttribute(a.a.moduleAttribute):"",j=j.replace(/::/g,"-").substr(0,40));f?(h&&(h="/"+h),h="*[@id='"+f.id+"']"+h,f=ec(b)):f=h;h=ja(h);f=ja(f);b=Ub(b,g,i);c={left:b.x,top:b.y,path:a.a[H],href:d,Wa:h,Aa:f,Va:"",Ra:c,Ka:0,Lb:a.a[I],
Ja:j};a.ia(c);e||a.q.update("_chartbeat5",wc(c),60,m,g,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function tc(a){return[a.left,a.top,a.Wa,encodeURIComponent(a.Va),a.Ra,encodeURIComponent(a.href),a.Aa,a.Ja].join("::")}function wc(a){var b=encodeURIComponent(a.Va),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Wa,b,a.Ra,a.Aa,encodeURIComponent(a.Lb),a.Ja].join(",")}
function sc(a){var b=a.q.k("_chartbeat5");if(!b)return l;var c=b.split("::"),b=c.length,d,e=l,f,h=uc(o.location.href),j=Ta(h);p(c,function(a,b){var c=a.split(","),h=decodeURIComponent(c[3]);if(h){h=za(j,h);if(h===0)return d=c,e=b,m;else if(h===l)return i;if(f===g||h<f)f=h,d=c,e=b}});if(e===l)return l;c.splice(e,1);a.q.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),
Wa:d[4]||"",Va:"",Aa:d.length>7?d[7]:"",Ra:d.length>6?d[6]:"c",Ka:b,Ja:d[9]?d[9]:""}}n.terminate=function(){db(B,this.Bb);db(B,this.Cb);X.P.terminate.call(this)};function xc(a,b){return function(c,d){if(!F){a();var e=o._sf_async_config,f="",h=e[H],h=na(h);/^\//.test(h)&&(f=u(o.location.hostname));e[tb]=Da()+"//"+f+h;if(z(c))e[H]=N(c),d&&(e[J]=d);else if(Ea(c)){var j=["authors","sections",J,H];p(c,function(a,b){if(Fa(j,function(a){return a===b})!==-1||b.indexOf("_")===0)e[b]=b===H?N(a):a})}b()}}};if(!L.k("cb_optout")&&!o.pSUPERFLY){var yc=new X,Y={};o.pSUPERFLY=Y;var Lc=o.pSUPERFLY_mab,$=o.pSUPERFLY_pub,Mc=[];Lc&&Mc.push(Lc);if($)Mc.push($),$.addEngagedAdFilter&&(Y.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Y.refreshAd=$.refreshAd),$.registerGptSlot&&(Y.registerGptSlot=$.registerGptSlot),ub("_cba",function(a){a()});Y.virtualPage=xc(function(){yc.oa();p(Mc,function(a){a.evps()})},function(){yc.qb();p(Mc,function(a){a.svps()})});Y.activity=r(yc.yb,yc);Mb(yc);var Nc=M.B(i);if(!Nc?
0:Nc.getItem("_cb_ip")){var Oc=o.location;(!/^(.+[.])?chartbeat\.com$/.test(Oc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Oc.pathname))||pc()}else x(o,"message",qc)};})();
